### ISSUE TITLE
Modrinth Equivalent Endpoint Tracker

### ISSUE THREAD

**Issue by StartsMercury** [CRModders/cosmic-mod-manager#38]
* [ ] `/search`
* [ ] `/project/{id|slug}`
* [ ] `/projects`
* [ ] `/projects_random`
* [ ] `/project`
* [ ] `/project/{id|slug}/icon`
* [ ] `/project/{id|slug}/check`
* [ ] `/project/{id|slug}/gallery`
* [ ] `/project/{id|slug}/dependencies`
* [ ] `/project/{id|slug}/follow`
* [ ] `/project/{id|slug}/schedule`
* [ ] `/project/{id|slug}/version`
* [ ] `/version/{id}``
* [ ] `/project/{id|slug}/version/{id|number}``
* [ ] `/version`
* [ ] `/version/{id}/schedule`
* [ ] `/versions`
* [ ] `/version/{id}/file`
* [ ] `/version_file/{hash}``
* [ ] `/version_file/{hash}/update`
* [ ] `/version_files`
* [ ] `/version_files/update`
* [ ] `/user/{id|username}``
* [ ] `/user`
* [ ] `/users`
* [ ] `/user/{id|username}/icon`
* [ ] `/user/{id|username}/projects`
* [ ] `/user/{id|username}/follows`
* [ ] `/user/{id|username}/payouts`
* [ ] `/user/{id|username}/notifications`
* [ ] `/notification/{id}``
* [ ] `/notifications`
* [ ] `/report`
* [ ] `/report/{id}``
* [ ] `/reports`
* [ ] `/thread/{id}``
* [ ] `/threads`
* [ ] `/message/{id}``
* [ ] `/project/{id|slug}/members`
* [ ] `/team/{id}/members`
* [ ] `/teams`
* [ ] `/team/{id}/join`
* [ ] `/team/{id}/members/{id|username}``
* [ ] `/team/{id}/owner`
* [ ] `/tag/category`
* [ ] `/tag/loader`
* [ ] `/tag/game_version`
* [ ] `/tag/license`
* [ ] `/tag/license/{id}``
* [ ] `/tag/donation_platform`
* [ ] `/tag/report_type`
* [ ] `/tag/project_type`
* [ ] `/tag/side_type`
* [ ] `/updates/{id|slug}/forge_updates.json`
* [ ] `/statistics`

**Comment by Abhinav5383** [comment]
that's great btw
